server:
  port:
    8080
spring:
  jackson-date-format: yyyy-MM-dd HH:mm:ss
logging:
  level:
    com:
      hotel:
        demo:
          controller: INFO
          persistence: INFO
          service: INFO
folder: "hotelReservations.json"